FROM node:16.15.1-alpine AS development

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --only=development

COPY . .

RUN yarn run build

FROM node:16.15.1-alpine AS production

WORKDIR /app

COPY database.json package.json yarn.lock ./

RUN yarn install --only=production

COPY migrations ./migrations

COPY --from=development /app/dist ./dist

CMD ["node", "/app/dist/main"]