version: '3.8'
services:
  db:
    container_name: db
    image: postgres:14.4-alpine
    ports:
      - 8010:5432
    volumes:
      - /app/pocket-bot/db:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
  migration:
    container_name: migration
    image: antgoncharik/pocket-bot
    env_file:
      - .env
    command: sh -c "/app/node_modules/.bin/db-migrate up"
    depends_on:
      db:
        condition: service_healthy
  server:
    container_name: server
    image: antgoncharik/pocket-bot
    ports:
      - '8011:3000'
    env_file:
      - .env
    restart: always
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
