name: production

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  SSH: ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
  DOCKER_RUN: ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} docker-compose -f pocket-bot/docker-compose.production.yml

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_IMAGE_NAME }} -f Dockerfile.production .

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_IMAGE_NAME }}

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: SSH setting
        run: |
          mkdir ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa

      - name: Settings docker-compose and env
        run: |
          ${{ env.SSH }} rm -rf pocket-bot
          ${{ env.SSH }} mkdir pocket-bot

          cat docker-compose.production.yml | ${{ env.SSH }} 'cat > pocket-bot/docker-compose.production.yml'

          ${{ env.SSH }} echo 'HOST=${{ secrets.HOST }} >> pocket-bot/.env'
          ${{ env.SSH }} echo 'TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} >> pocket-bot/.env'
          ${{ env.SSH }} echo 'TELEGRAM_BOT_HOST=${{ secrets.TELEGRAM_BOT_HOST }} >> pocket-bot/.env'
          ${{ env.SSH }} echo 'POCKET_CONSUMER_KEY=${{ secrets.POCKET_CONSUMER_KEY }} >> pocket-bot/.env'
          ${{ env.SSH }} echo 'POCKET_HOST=${{ secrets.POCKET_HOST }} >> pocket-bot/.env'
          ${{ env.SSH }} echo 'DB_HOST=${{ secrets.DB_HOST }} >> pocket-bot/.env'
          ${{ env.SSH }} echo 'DB_PORT=${{ secrets.DB_PORT }} >> pocket-bot/.env'
          ${{ env.SSH }} echo 'DB_USER=${{ secrets.DB_USER }} >> pocket-bot/.env'
          ${{ env.SSH }} echo 'DB_NAME=${{ secrets.DB_NAME }} >> pocket-bot/.env'
          ${{ env.SSH }} echo 'DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> pocket-bot/.env'
          ${{ env.SSH }} echo 'DB_DRIVER=${{ secrets.DB_DRIVER }} >> pocket-bot/.env'
          ${{ env.SSH }} echo 'POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> pocket-bot/.env'
          ${{ env.SSH }} echo 'POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> pocket-bot/.env'
          ${{ env.SSH }} echo 'POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> pocket-bot/.env'
          ${{ env.SSH }} echo 'PGPORT=${{ secrets.PGPORT }} >> pocket-bot/.env'

      - name: Stop containers
        run: ${{ env.DOCKER_RUN }} down

      - name: Run containers
        run: ${{ env.DOCKER_RUN }} up -d --build
